### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.tomcat.util.scan.StandardJarScanner.setJarScanFilter(Lorg/apache/tomcat/JarScanFilter;)V

### ISSUE THREAD

**Issue by leiguorui** [paulc4/microservices-demo#12]
Hi Paul,  I am getting a exception like below when I am trying to run RegistrationServer.java.  Could you please help me?

> org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.NoSuchMethodError: org.apache.tomcat.util.scan.StandardJarScanner.setJarScanFilter(Lorg/apache/tomcat/JarScanFilter;)V
>     at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:133)
>     at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
>     at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
>     at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
>     at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
>     at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
>     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191)
>     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180)
>     at io.pivotal.microservices.services.registration.RegistrationServer.main(RegistrationServer.java:28)

**Comment by paulc4** [comment]
This may be due to a conflict.  Are you running the application as a java application.    It is not intended to run as a war inside a separate container.  How are you running the application?
