### ISSUE TITLE
Test errors: java.lang.IllegalArgumentException: Cannot find class [org.hibernate.cfg.ImprovedNamingStrategy]]

### ISSUE THREAD

**Issue by MaxHoefl** [paulc4/microservices-demo#28]
I get `java.lang.IllegalArgumentException: Cannot find class [org.hibernate.cfg.ImprovedNamingStrategy]]` when I do `mvn clean package`

Please see this question:
https://stackoverflow.com/questions/47891864/spring-boot-java-lang-nosuchfielderror-parallelcapableclassloaderavailable

**Comment by paulc4** [comment]
Just did a clean clone and it built perfectly, of course!  I'm using maven 3.3.9 and Java 1.8.0_73.

I'm working on upgrading the whole project to later versions of Boot and Cloud anyway.

**Comment by paulc4** [comment]
I have upgraded to Spring Boot 1.5 and Spring Cloud Edgeware, please try again.

**Comment by paulc4** [comment]
Open for too long, closing.
