### ISSUE TITLE
Blog link in README.md needs to be updated

### ISSUE THREAD

**Issue by ssmythe** [paulc4/microservices-demo#3]
It looks like the README.md has a link to your blog article that isn't quite right:

> Demo application to go with my [Microservices Blog](https://spring.io/admin/blog/2181-microservices-with-spring) on the spring.io website.

Should this link point to:

> Demo application to go with my [Microservices Blog](https://spring.io/blog/2015/07/14/microservices-with-spring) on the spring.io website.

...?

Steve

**Comment by paulc4** [comment]
Done, thanks.
