### ISSUE TITLE
I get an error in the POM when trying to build/run

### ISSUE THREAD

**Issue by bhattacharyyasom** [paulc4/microservices-demo#5]
I get this error after i import the project in STS. Also i see the error when i try to run mvn build.

Project build error: Non-resolvable parent POM for org.springframework.samples.service.service:microservice-demo:0.0.1-SNAPSHOT: Failure to 
 transfer org.springframework.cloud:spring-cloud-starter-parent:pom:Angel.SR3 from https://repo.maven.apache.org/maven2 was cached in the local 
 repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer 
 artifact org.springframework.cloud:spring-cloud-starter-parent:pom:Angel.SR3 from/to central (https://repo.maven.apache.org/maven2): Failed to 
 transfer file: https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-starter-parent/Angel.SR3/spring-cloud-starter-parent-
 Angel.SR3.pom. Return code is: 400 , ReasonPhrase:Bad Request. and 'parent.relativePath' points at wrong local POM

**Comment by ewolff** [comment]
Thanks for raising the issue. Something very similar just happened to me.

I ran `mvn -e` to get more debug output and noticed `java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty` . Essentially this is a problem with outdated SSL certificates. http://askubuntu.com/questions/627426/minecraft-with-openjdk-7-i-get-the-trustanchors-parameter-must-be-non-empty gives some hint how to solve that issue.

**Comment by paulc4** [comment]
I have upgraded the pom to Brixton.RELEASE.  Has this problem gone away?

**Comment by ewolff** [comment]
As I said above - this is very likely due to outdated SSL certificates on your machine or other issues that prevent you from loading the Maven dependencies. I am afraid this is specific to your machine and I cannot really offer a lot of help, sorry. You can try https://github.com/ewolff/microservices-vm and see whether the software complies in a VM.

**Comment by paulc4** [comment]
So this is not an issue with the application.  Can I close this?

**Comment by ewolff** [comment]
If you agree with what I said - yes, please :-)
